# Generated by Django 4.2.20 on 2025-04-02 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SustainabilityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("industry", models.FileField(upload_to="")),
                ("carbon_score", models.FloatField(default=0)),
                ("electricity_usage", models.FloatField(default=0)),
                ("gas_consumption", models.FloatField(default=0)),
                ("energy_total", models.FloatField(default=0)),
                ("electricity_kwh", models.FloatField(default=0)),
                ("total_waste", models.FloatField(default=0)),
                ("waste_reduction_rate", models.FloatField(default=0)),
                ("recycled_waste", models.FloatField(default=0)),
                ("eevta_score", models.FloatField(default=0)),
                ("total_students", models.IntegerField(default=0)),
                ("tech_voc_percentage", models.FloatField(default=0)),
                ("roi", models.FloatField(default=0)),
                ("cost_benefit", models.FloatField(default=0)),
                ("sustainability_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalculationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carbon_emissions", models.FloatField()),
                ("energy_consumption", models.FloatField()),
                ("waste_production", models.FloatField()),
                ("evtaa_score", models.FloatField()),
                ("revenue", models.FloatField()),
                ("costs", models.FloatField()),
                ("investment", models.FloatField()),
                ("sustainability_score", models.FloatField()),
                ("roi", models.FloatField()),
                ("cost_benefit", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.sustainabilityprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Calculation Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
