# Generated by Django 4.2.20 on 2025-04-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calculationhistory",
            old_name="evtaa_score",
            new_name="eevta_score",
        ),
    ]
